### ISSUE TITLE
tried using it but getting an error

### ISSUE THREAD

**Issue by technovangelist** [Lutzifer/keyboardSwitcher#1] opened 2015-12-23 17:23 UTC
`> keyboardSwitcher select "Workman-Dead"
2015-12-23 12:22:14.576 keyboardSwitcher[29853:10912361] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 7. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2015-12-23 12:22:14.577 keyboardSwitcher[29853:10912361] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 7. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2015-12-23 12:22:14.579 keyboardSwitcher[29853:10912361] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 7. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2015-12-23 12:22:14.580 keyboardSwitcher[29853:10912361] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 7. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2015-12-23 12:22:14.580 keyboardSwitcher[29853:10912361] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 7. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2015-12-23 12:22:14.580 keyboardSwitcher[29853:10912361] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 7. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2015-12-23 12:22:14.580 keyboardSwitcher[29853:10912361] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 7. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2015-12-23 12:22:14.580 keyboardSwitcher[29853:10912361] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 7. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2015-12-23 12:22:14.580 keyboardSwitcher[29853:10912361] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 7. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2015-12-23 12:22:14.580 keyboardSwitcher[29853:10912361] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 7. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2015-12-23 12:22:14.588 keyboardSwitcher[29853:10912361] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 7. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2015-12-23 12:22:14.588 keyboardSwitcher[29853:10912361] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 7. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
Failed to set the layout "org.sil.ukelele.keyboardlayout.workman.keylayout.Workman-Dead".
Layout "org.sil.ukelele.keyboardlayout.workman.keylayout.Workman-Dead" known, but could not be set: Please add the layout in System Preferences.app > Keyboard > Input Sources to fix this.`

**Comment by Lutzifer** [comment] 2015-12-25 20:03
Do you have "Workman-Dead" in your Input Sources?

see "Layout "org.sil.ukelele.keyboardlayout.workman.keylayout.Workman-Dead" known, but could not be set: Please add the layout in System Preferences.app > Keyboard > Input Sources to fix this."

Also, what version of OS X are you using it on?

**Comment by technovangelist** [comment] 2015-12-25 23:37
## I have that and U.S. And that's all I use

Matt Williams

**Comment by Lutzifer** [comment] 2015-12-26 09:24
Ok. What version of OSX do you use?

I will further investigate this issue in January.

**Comment by technovangelist** [comment] 2015-12-26 15:21
## El Capitan

Matt Williams

**Comment by lgtout** [comment] 2016-01-02 03:21
Interesting.  I'm not using this project, but I have a similar [issue](http://stackoverflow.com/q/34562149/369722) when starting groovysh.  And I too use Workman.

![screenshot_1_1_16__7_19_pm](https://cloud.githubusercontent.com/assets/364799/12073066/a3e08290-b0bc-11e5-91f7-5f1a16a5ebbc.png)

**Comment by Lutzifer** [comment] 2016-01-02 08:07
Thanks for the information, that is an interesting similar issue.

**Comment by technovangelist** [comment] 2016-01-04 22:27
here is what i see: 
![screen shot 2016-01-04 at 5 26 29 pm](https://cloud.githubusercontent.com/assets/633681/12102386/67bfce3a-b308-11e5-816e-b394c0f17fb4.png)

**Comment by technovangelist** [comment] 2016-01-04 22:29
and keyboardswitcher list gets me:

```
~ > keyboardSwitcher list
2016-01-04 17:28:39.502 keyboardSwitcher[52691:24347910] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 7. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2016-01-04 17:28:39.503 keyboardSwitcher[52691:24347910] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 7. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2016-01-04 17:28:39.510 keyboardSwitcher[52691:24347910] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 7. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2016-01-04 17:28:39.511 keyboardSwitcher[52691:24347910] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 7. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2016-01-04 17:28:39.511 keyboardSwitcher[52691:24347910] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 7. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2016-01-04 17:28:39.511 keyboardSwitcher[52691:24347910] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 7. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2016-01-04 17:28:39.511 keyboardSwitcher[52691:24347910] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 7. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2016-01-04 17:28:39.511 keyboardSwitcher[52691:24347910] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 7. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2016-01-04 17:28:39.511 keyboardSwitcher[52691:24347910] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 7. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2016-01-04 17:28:39.511 keyboardSwitcher[52691:24347910] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 7. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2016-01-04 17:28:39.511 keyboardSwitcher[52691:24347910] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 7. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2016-01-04 17:28:39.511 keyboardSwitcher[52691:24347910] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 7. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
Available Layouts:
    2-Set Korean
    3-Set Korean
    390 Sebulshik
    ABC
    ABC - AZERTY
    ABC - QWERTZ
    ABC Extended
    Afghan Dari
    Afghan Pashto
    Afghan Uzbek
    Anjal
    Arabic
    Arabic - AZERTY
    Arabic - North Africa
    Arabic - PC
    Arabic - QWERTY
    Armenian - HM QWERTY
    Armenian - Western QWERTY
    Australian
    Austrian
    Azeri
    Bangla
    Bangla - QWERTY
    Belarusian
    Belgian
    Brazilian
    Brazilian - ABNT2
    Brazilian - Pro
    British
    British - PC
    Bulgarian
    Bulgarian - Phonetic
    Canadian English
    Canadian French - CSA
    Cangjie
    Cherokee - Nation
    Cherokee - QWERTY
    Colemak
    Croatian
    Croatian - PC
    Czech
    Czech - QWERTY
    Danish
    Devanagari
    Devanagari - QWERTY
    Dutch
    Dvorak
    Dvorak - Left
    Dvorak - Qwerty \u2318
    Dvorak - Right
    Estonian
    Faroese
    Finnish
    Finnish Extended
    Finnish Sami - PC
    French
    French - Numerical
    French - PC
    Georgian - QWERTY
    German
    GongjinCheong Romaja
    Greek
    Greek Polytonic
    Gujarati
    Gujarati - QWERTY
    Gurmukhi
    Gurmukhi - QWERTY
    Hawaiian
    Hebrew
    Hebrew - PC
    Hebrew - QWERTY
    HNC Romaja
    Hungarian
    Hungarian - QWERTY
    Icelandic
    Inuktitut - Nunavut
    Inuktitut - Nutaaq
    Inuktitut - QWERTY
    Inuktitut Nunavik
    Irish
    Irish Extended
    Italian
    Italian Typewriter
    Jawi - QWERTY
    Kana
    Kannada
    Kannada - QWERTY
    Kazakh
    Khmer
    Kurdish - Sorani
    Latvian
    Lithuanian
    Macedonian
    Malayalam
    Malayalam - QWERTY
    Maltese
    Maori
    Myanmar - QWERTY
    Nepali
    Northern Sami
    Norwegian
    Norwegian Extended
    Norwegian Sami - PC
    Oriya
    Oriya - QWERTY
    Persian
    Persian - ISIRI
    Persian - QWERTY
    Polish
    Polish Pro
    Portuguese
    Romanian
    Romanian - Standard
    Russian
    Russian - PC
    Russian - Phonetic
    Sami - PC
    Serbian
    Serbian - Latin
    Sinhala
    Sinhala - QWERTY
    Slovak
    Slovak - QWERTY
    Slovenian
    Spanish
    Spanish - ISO
    Stroke
    Swedish
    Swedish - Pro
    Swedish Sami - PC
    Swiss French
    Swiss German
    Tamil99
    Telugu
    Telugu - QWERTY
    Thai
    Thai - PattaChote
    Tibetan - Otani
    Tibetan - QWERTY
    Tibetan - Wylie
    Tongan
    Turkish
    Turkish - QWERTY
    Turkish - QWERTY PC
    U.S.
    U.S. International - PC
    Ukrainian
    Ukrainian - PC
    Unicode Hex Input
    Urdu
    Uyghur
    Vietnamese
    Welsh
    Workman
    Workman Extended
    Workman-Dead
    Workman-IO
    Workman-P
    Workman-P Extended
    Wubi Xing
    Zhuyin
    Zhuyin - Eten
```

**Comment by Lutzifer** [comment] 2016-01-18 22:49
So, this was caused by two different Bugs.
The "CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line " error is due to a missing semicolon in the workman project, see https://github.com/ojbucao/Workman/pull/27

the issue, that the keyboard was not found was fixed by https://github.com/Lutzifer/keyboardSwitcher/commit/39cae00236dc35faa057ac10e7d871cfde25cb84

**Closed as completed** 2016-01-18 22:49 UTC

**Comment by lgtout** [comment] 2016-01-19 03:41
@Lutzifer Thanks for looking into this.  I added the missing semicolon locally and that fixed the problem.

**Comment by technovangelist** [comment] 2016-01-19 15:43
I also made the change, but now when i do keyboardSwitcher select Workman-Dead i get:

`Failed to set the layout "org.sil.ukelele.keyboardlayout.workman.keylayout.Workman-Dead".
Layout "org.sil.ukelele.keyboardlayout.workman.keylayout.Workman-Dead" known, but could not be set: Please add the layout in System Preferences.app > Keyboard > Input Sources to fix this.`

![image](https://cloud.githubusercontent.com/assets/633681/12423426/67e948e0-be99-11e5-8253-540a4dc12b55.png)

but I already do

**Comment by technovangelist** [comment] 2016-01-19 15:44
I changed it using the mac interface and keyboardswitcher get then shows Workman-Dead, but get the same error if i try to set it to Workman-Dead

**Comment by Lutzifer** [comment] 2016-01-19 15:44
did you update keyboardSwitcher?

brew update
brew upgrade keyboardSwitcher

**Comment by technovangelist** [comment] 2016-01-19 15:46
ahhh , no i hadn't. I have now and it works perfectly, thanks so much

**Comment by Lutzifer** [comment] 2016-01-19 15:47
glad that it is of use to you 😃
